# Generated by Django 5.1.2 on 2024-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionstats',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
